replicaCount: 1

rte:
  name: rteweb
  image: registry.rocketsoftware.com/rte:10.1.5.0065


ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: "32m"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "session-cookie"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/session-cookie-change-on-failure: "false"
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-path: /
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
  hosts:
    - host: rte.banorte.com
      paths:
        - path: /(.*)$
          pathType: ImplementationSpecific
  #tls:
  #  - hosts:
  #    - services-us-virginia-m-1.skytap.com
  #    secretName: "tls-rocket"  # rte.rocket-sandbox.net