apiVersion: v1
kind: Service
metadata:
  labels:
    app:  {{ .Values.rte.name }} 
  name:  {{ .Values.rte.name }} 
spec:
  type: {{ .Values.service.type }} 
  ports:
  - name: "http"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app:  {{ .Values.rte.name }} 
